#!/bin/bash
 
 echo " "
 echo "= = = = = = = = = = = "
 echo "PATH $PATH" | tr ':' '\n'
 
 echo " "
 echo "= = = = = = = = = = = "
 echo "loading nvm ..."
 curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh | bash
 
 # make nvm available immediately
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
 
 echo " "
 echo "= = = = = = = = = = = "
 echo "Is nvm installed?"
 command -v nvm
 nvm --version
 
 # based on this recommendation in the error logs
 # nvm is not compatible with the npm config "prefix" option: currently set to "/home/pipeline/.npm-global"
 # Run `npm config delete prefix` or `nvm use --delete-prefix v11.2.0` to unset it.
 echo " "
 echo "= = = = = = = = = = = "
 echo "config delete prefix..."
 npm config delete prefix
 
 
 echo " "
 echo "= = = = = = = = = = = "
 echo "Installing the latest version of nodejs"
 nvm install node
 
 
 echo " "
 echo "= = = = = = = = = = = "
 echo "Which node version is it?"
 node -v
 
 echo " "
 echo "= = = = = = = = = = = = = = = = = = ="
 echo "prepare to load nvm in the next stage"
 # do not do this with every build.  It only needs to be added once.
 echo 'export NVM_DIR="$HOME/.nvm" ' >> /home/pipeline/.bashrc
 echo '[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm ' >> /home/pipeline/.bashrc
 echo '[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion ' >> /home/pipeline/.bashrc
 export REACT_APP_SERVER="http://chatbotfacmedbackend.germfy.com"
 echo " "
 echo "= = = = = = = = = = = = = = = = = = ="
 echo "contents of /home/pipeline/.bashrc:"

 cat /home/pipeline/.bashrc

 npm install && npm run build
 
 echo " Finished!"
